### ISSUE TITLE
Highcharts JS and other feedback from Ft Collins IT team

### ISSUE THREAD

**Issue by catherine-yochum** [ClearPoint-Strategy/wp-clearpoint#6]
Hi Steven,

Jolene sent me a few points of feedback from the Fort Collins IT team, and I didn't understand the following:

- "The HighCharts JS library is being loaded twice, causing JavaScript errors in some browsers."
- "We need to index this site with our search appliance so we can return search results on our website.  Until we point our search appliance at this site we won’t know if it will properly crawl URLs identified inside ‘onclick’ events.  If not, we may need those onclick events to get changed to anchor tags.  Search engines other than Google may also have a hard time crawling links that use onclick events instead of anchor tags."
- "Is there a RSS feed available for this site?  It would make things easier for us to consume the feed rather than manually updating content on our end."

Do you know what any of these mean, or how to resolve them? They want to go live Thursday or Friday, so I'd like to resolve these as soon as we can.

Thanks!

Catherine

**Comment by stguitar** [comment]
Yes, I understand the request but we should discuss internally who's responsibility they are. Item 1 is us but maybe not the other too.

Also, this is fine as an email, not an issue in github.

Let's discuss tomorrow.

Sent from my iPhone

On Feb 16, 2016, at 6:41 PM, catherine-yochum <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Steven,

Jolene sent me a few points of feedback from the Fort Collins IT team, and I didn't understand the following:

  *   "The HighCharts JS library is being loaded twice, causing JavaScript errors in some browsers."
  *   "We need to index this site with our search appliance so we can return search results on our website. Until we point our search appliance at this site we won’t know if it will properly crawl URLs identified inside ‘onclick’ events. If not, we may need those onclick events to get changed to anchor tags. Search engines other than Google may also have a hard time crawling links that use onclick events instead of anchor tags."
  *   "Is there a RSS feed available for this site? It would make things easier for us to consume the feed rather than manually updating content on our end."

Do you know what any of these mean, or how to resolve them? They want to go live Thursday or Friday, so I'd like to resolve these as soon as we can.

Thanks!

Catherine

**Comment by stguitar** [comment]
1. we are going to look into and fix as needed

2. they need to tell us where the problems are and either they or us would make the changes.  i also think we should ask Ted about the line of that is a CPS thing to do, or a FtC thing to do.  They need to definitely find the problem spots, but then any wordpress content that has been made that needs to change needs to be updated and i dont know who should really do that work. 

3. wordpress seems to support a built in RSS stream, but it looks to need configuring:  https://fortcollins.clearpointstrategy.com/feed/  - > how, I am not entirely sure at this point in time.  also, who should take that role on should be figured out with Ted as well. I could easily see that falling to them.

**Comment by stguitar** [comment]
OH, and the RSS thing that comes with wordpress that I pointed you to doesnt include pages, but instead just wordpress blog entries.  Since all of our stuff is done on pages, it wont really capture that, however there are plugins that you can get to add that content to the feed.

**Comment by ted-jackson** [comment]
I don't know that any of this is our problem, is it?  I mean these are new requirements in my mind.  If they want to host this site, I think we can look at how to transfer this over to them.

Can we set up Google Analytics on this site or something just to let them know how often it is being hit?  I would think we could let Jolene do some SEO stuff on the site, but that is not our responsibility, IMHO.

**Comment by ted-jackson** [comment]
You guys can both capture Lawrence in Ft. Lauderdale.

**Comment by stguitar** [comment]
I agree completely.

Item 1 is something that is in the plugin, it seems. Should have that resolved for them but the rest, yea, not really the plugin but how they want to setup wordpress.

**Comment by catherine-yochum** [comment]
Hi Steven,

Ok, I’m not sure how much time we will have between landing and training, but I should be free to discuss around 5 or 5:30 if that works for you! I’ll ping you if we end up having more time than I think.

Thanks!!
Catherine

-----------------------------------------------------------
Catherine Yochum
ClearPoint Strategy
cyochum@clearpointstrategy.com<mailto:cyochum@clearpointstrategy.com> | 866-568-0590
www.clearpointstrategy.com<http://www.clearpointstrategy.com/> | @clearpointstrat
